// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['usecase']['SettingsUsecase']['GetSettings']();
}

export function SetDarkTheme(arg1) {
  return window['go']['usecase']['SettingsUsecase']['SetDarkTheme'](arg1);
}
