// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {output} from '../models';

export function GetSettings():Promise<output.SettingsOutput>;

export function SetDarkTheme(arg1:boolean):Promise<void>;
