// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {uuid} from '../models';
import {input} from '../models';
import {output} from '../models';

export function CompleteTask(arg1:uuid.UUID):Promise<void>;

export function CreateTask(arg1:input.TaskCreateInput):Promise<void>;

export function DeleteTask(arg1:uuid.UUID):Promise<void>;

export function GetTasks():Promise<Array<output.TaskOutput>>;

export function UncompleteTask(arg1:uuid.UUID):Promise<void>;

export function UpdateTitle(arg1:uuid.UUID,arg2:input.TaskUpdateInput):Promise<void>;
