// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteTask(arg1) {
  return window['go']['usecase']['TaskUsecase']['CompleteTask'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['usecase']['TaskUsecase']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['usecase']['TaskUsecase']['DeleteTask'](arg1);
}

export function GetTasks() {
  return window['go']['usecase']['TaskUsecase']['GetTasks']();
}

export function UncompleteTask(arg1) {
  return window['go']['usecase']['TaskUsecase']['UncompleteTask'](arg1);
}

export function UpdateTitle(arg1, arg2) {
  return window['go']['usecase']['TaskUsecase']['UpdateTitle'](arg1, arg2);
}
